### ISSUE TITLE
Helm Charts Pointing to Repo Panics

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#11]
**Describe the bug**
Running this panics.
 `go run main.go convert --api-version=apps.example.com/v1aplha1 --helm-chart ngnix --helm-chart-repo=https://helm.nginx.com/stable`

Doesn't do cmd args validations.
 `go run main.go convert ---helm-chart-repo=https://helm.nginx.com/stable`

```shell
go run main.go convert --api-version=apps.example.com/v1aplha1 --helm-chart ngnix --helm-chart-repo=https://helm.nginx.com/stable
[2019-07-02 13:42:34] 🤠 Converting Existing Helm Chart ngnix to Go Operator!      
[2019-07-02 13:42:34] Chart Is Empty! Exiting
                                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe68403]

goroutine 1 [running]:
github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert.loadChart()
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert/chart.go:23 +0x63
github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert.convertFunc(0xc4203fa280, 0xc4203c6380, 0x0, 0x4, 0x0, 0x0)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert/cmd.go:57 +0x159
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203fa280, 0xc4203c6340, 0x4, 0x4, 0xc4203fa280, 0xc4203c6340)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:826 +0x468
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203fa000, 0x0, 0xc4203fa280, 0xc4203fa150)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:914 +0x306
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203fa000, 0xc4200e9f70, 0x1)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:864 +0x2b
main.main()
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/main.go:32 +0xcb
exit status 2
```

**Expected behavior**

**Comment by sjakati98** [comment]
Addressed in a9f053461f8c3033300631187dc882a2248e2c23
